Repository Learn-Run/front, pull requests merged in 2025-06, with the labels that each got.

#51 feat: checkbox input 컴포넌트 추가
  packages/ui/package.json
  packages/ui/src/components/base/Checkbox.tsx
  pnpm-lock.yaml
Labels: enhancement

#61 feat: heroSection 버튼 추가
  apps/pick-learn/src/views/home/ui/HeroSection.tsx
  apps/pick-learn/src/views/home/ui/TopAskSection.tsx
  packages/ui/src/components/wrapper/TypingWrapper.tsx
Labels: enhancement

#72 feat: useDebounce 훅 추가
  apps/pick-learn/src/shared/model/useDebounce.ts
Labels: enhancement

#74 feat: date picker
  apps/pick-learn/src/shared/assets/icons/IconCalendar.tsx
  apps/pick-learn/src/shared/assets/icons/index.ts
  apps/pick-learn/src/shared/utils/dateFormat.ts
  packages/ui/package.json
  packages/ui/src/components/base/Calendar.tsx
  packages/ui/src/components/base/Popover.tsx
  pnpm-lock.yaml
Labels: enhancement

#77 feat: sign up
  apps/pick-learn/eslint.config.mjs
  apps/pick-learn/middleware.ts
  apps/pick-learn/package.json
  apps/pick-learn/src/app/(home)/(auth)/sign-up/page.tsx
  apps/pick-learn/src/features/auth/api/index.ts
  apps/pick-learn/src/features/auth/api/types.ts
  apps/pick-learn/src/features/auth/constants.ts
  apps/pick-learn/src/features/auth/model/applyServerFields.ts
  apps/pick-learn/src/features/auth/model/constants.ts
  apps/pick-learn/src/features/auth/model/hooks/useAgreeTerms.ts
  apps/pick-learn/src/features/auth/model/schema.ts
  apps/pick-learn/src/features/auth/model/types.ts
  apps/pick-learn/src/features/auth/ui/AgreeAllTermsCheckbox.tsx
  apps/pick-learn/src/features/auth/ui/AgreeTermCheckbox.tsx
  apps/pick-learn/src/features/auth/ui/SignUpButton.tsx
  apps/pick-learn/src/features/auth/ui/SignUpForm.tsx
  apps/pick-learn/src/features/auth/ui/SignUpStepRenderer.tsx
  apps/pick-learn/src/features/auth/ui/index.ts
  apps/pick-learn/src/features/auth/ui/steps/SignUpStep1.tsx
  apps/pick-learn/src/features/auth/ui/steps/SignUpStep2.tsx
  apps/pick-learn/src/features/auth/ui/steps/SignUpStep3.tsx
  apps/pick-learn/src/features/auth/ui/steps/SignUpStep4.tsx
  apps/pick-learn/src/features/auth/ui/types.ts
  apps/pick-learn/src/features/auth/utils/getCurrentStepValidation.ts
  apps/pick-learn/src/shared/assets/icons/Jobs.tsx
  apps/pick-learn/src/shared/ui/index.ts
  apps/pick-learn/src/views/auth/ui/SignUpContainer.tsx
  apps/pick-learn/src/widgets/layout/ui/Header.tsx
  packages/eslint-config/base.js
  packages/ui/src/components/base/Input/types.ts
  pnpm-lock.yaml
Labels: enhancement

#83 Refactor/topasksection
  apps/pick-learn/src/entities/member/api/types.ts
  apps/pick-learn/src/entities/member/ui/Profile.tsx
  apps/pick-learn/src/entities/post/api/types.ts
  apps/pick-learn/src/views/home/ui/AskItemCardList.tsx
  apps/pick-learn/src/views/home/ui/TopAnswererCardList.tsx
Labels: refactor

#86 feat: sign up api 연결
  apps/pick-learn/src/app/(home)/(auth)/sign-up/page.tsx
  apps/pick-learn/src/app/api/auth/[...nextauth]/options.ts
  apps/pick-learn/src/features/auth/api/index.ts
  apps/pick-learn/src/features/auth/api/types.ts
  apps/pick-learn/src/features/auth/model/constants.ts
  apps/pick-learn/src/features/auth/model/hooks/useAgreeTerms.ts
  apps/pick-learn/src/features/auth/model/schema.ts
  apps/pick-learn/src/features/auth/ui/SignUpForm.tsx
  apps/pick-learn/src/features/auth/ui/index.ts
  apps/pick-learn/src/features/auth/ui/steps/SignUpStep1.tsx
  apps/pick-learn/src/features/auth/ui/steps/SignUpStep2.tsx
  apps/pick-learn/src/features/auth/ui/steps/SignUpStep3.tsx
  apps/pick-learn/src/features/auth/ui/steps/SignUpStep4.tsx
  apps/pick-learn/src/shared/api/instance.ts
  apps/pick-learn/src/shared/model/hooks/useDebounce.ts
  apps/pick-learn/src/shared/model/hooks/useTimer.ts
  apps/pick-learn/src/shared/utils/dateFormat.ts
  packages/ui/package.json
  packages/ui/src/components/base/Calendar.tsx
  packages/ui/src/components/base/Input/index.tsx
  packages/ui/src/components/base/ScrollArea.tsx
  packages/ui/src/components/base/Stepper.tsx
  packages/ui/src/styles/default.css
  pnpm-lock.yaml
Labels: enhancement

#87 feat: post페이지 생성
  apps/pick-learn/src/app/(home)/post/page.tsx
  apps/pick-learn/src/entities/category/api/index.ts
  apps/pick-learn/src/entities/category/api/types.ts
  apps/pick-learn/src/entities/category/ui/CategoryListItem.tsx
  apps/pick-learn/src/entities/category/ui/SubCategoryItem.tsx
  apps/pick-learn/src/views/home/ui/AskItemCardList.tsx
  apps/pick-learn/src/views/post/ui/PostListSection.tsx
  apps/pick-learn/src/views/post/ui/PostTopSection.tsx
  apps/pick-learn/src/widgets/layout/constants.ts
  apps/pick-learn/src/widgets/layout/ui/SubMenu.tsx
  apps/pick-learn/src/widgets/layout/ui/index.ts
  packages/ui/src/components/base/Accordion.tsx
Labels: enhancement

#91 feat: service
  apps/pick-learn/src/app/api/auth/[...nextauth]/options.ts
  apps/pick-learn/src/entities/category/api/index.ts
  apps/pick-learn/src/features/auth/api/index.ts
  apps/pick-learn/src/shared/api/constants.ts
Labels: enhancement

#97 refactor: calendar css
  apps/pick-learn/src/app/api/auth/[...nextauth]/options.ts
  packages/ui/src/components/base/Calendar.tsx
Labels: refactor

#96 refactor: category 수정
  apps/pick-learn/src/entities/category/ui/CategoryListItem.tsx
  apps/pick-learn/src/entities/category/ui/SubCategoryItem.tsx
  apps/pick-learn/src/entities/post/api/types.ts
Labels: refactor

#99 refactor: 수정된 디자인에 맞게 헤더 수정
  apps/pick-learn/src/app/(home)/page.tsx
  apps/pick-learn/src/views/home/ui/CategoryCarousel.tsx
  apps/pick-learn/src/views/home/ui/CategorySection.tsx
  apps/pick-learn/src/views/home/ui/HeroSection.tsx
  apps/pick-learn/src/widgets/layout/ui/BottomNavBar.tsx
  apps/pick-learn/src/widgets/layout/ui/Header.tsx
Labels: refactor

#101 refactor: main 페이지 섹션 css 수정
  apps/pick-learn/public/images/SearchMonster.png
  apps/pick-learn/public/images/StepAnswererMonster.png
  apps/pick-learn/public/images/monster.png
  apps/pick-learn/src/entities/category/api/index.ts
  apps/pick-learn/src/entities/guide/model/constants.ts
  apps/pick-learn/src/entities/guide/ui/StepCard.tsx
  apps/pick-learn/src/entities/guide/ui/StepCardList.tsx
  apps/pick-learn/src/entities/guide/ui/StepCarouseList.tsx
  apps/pick-learn/src/shared/api/constants.ts
  apps/pick-learn/src/shared/ui/Wrapper/StepWrapper.tsx
  apps/pick-learn/src/views/home/ui/StepSection.tsx
  apps/pick-learn/src/views/home/ui/TopAnswererSection.tsx
  packages/ui/src/styles/default.css
Labels: refactor

#103 refactor:카테고리 api 변경
  apps/pick-learn/src/entities/category/api/index.ts
  apps/pick-learn/src/entities/category/api/types.ts
  apps/pick-learn/src/entities/category/ui/SubCategoryItem.tsx
Labels: refactor

#117 refactor: 헤더 로그인 버튼 다시 추가
  apps/pick-learn/src/widgets/layout/ui/SignButton.tsx
Labels: refactor

#120 refactor: post 페이지 수정
  apps/pick-learn/src/app/(home)/post/page.tsx
  apps/pick-learn/src/entities/category/api/constants.ts
  apps/pick-learn/src/entities/category/api/index.ts
  apps/pick-learn/src/entities/category/ui/CategoryListItem.tsx
  apps/pick-learn/src/entities/category/ui/SubCategoryItem.tsx
  apps/pick-learn/src/views/home/ui/CategorySection.tsx
  apps/pick-learn/src/views/home/ui/CreateCategoryButton.tsx
Labels: refactor

#123 feat: oauth sign up
  apps/pick-learn/src/app/(home)/(auth)/sign-up/page.tsx
  apps/pick-learn/src/app/api/auth/[...nextauth]/options.ts
  apps/pick-learn/src/features/auth/api/index.ts
  apps/pick-learn/src/features/auth/api/types.ts
  apps/pick-learn/src/features/auth/model/constants.ts
  apps/pick-learn/src/features/auth/model/schema.ts
  apps/pick-learn/src/features/auth/model/types.ts
  apps/pick-learn/src/features/auth/ui/CreateAgreementButton.tsx
  apps/pick-learn/src/features/auth/ui/CredentialsSignUpForm.tsx
  apps/pick-learn/src/features/auth/ui/OAuthSignIn.tsx
  apps/pick-learn/src/features/auth/ui/OAuthSignUpForm.tsx
  apps/pick-learn/src/features/auth/ui/SignInForm.tsx
  apps/pick-learn/src/features/auth/ui/index.ts
  apps/pick-learn/src/features/auth/ui/steps/OAuthSignUpStep2.tsx
  apps/pick-learn/src/features/auth/ui/steps/SignUpStep1.tsx
  apps/pick-learn/src/features/auth/ui/steps/SignUpStep3.tsx
  apps/pick-learn/src/features/auth/ui/types.ts
  apps/pick-learn/src/features/auth/utils/convertSignUpData.ts
  apps/pick-learn/src/views/auth/ui/SignUpContainer.tsx
Labels: enhancement

#129 feat: 게시물 정렬 publishing
  apps/pick-learn/src/app/(home)/post/page.tsx
  apps/pick-learn/src/entities/category/ui/SubCategoryItem.tsx
  apps/pick-learn/src/entities/category/utils/categorySearchParams.ts
  apps/pick-learn/src/shared/assets/icons/Filter.tsx
  apps/pick-learn/src/views/post/ui/PostFilterSection.tsx
  apps/pick-learn/src/views/post/ui/PostListSection.tsx
Labels: enhancement

#132 refactor: 모달이 켜졌을 경우 scroll hidden으로 변경될 수 있도록 수정
  apps/pick-learn/src/app/(home)/@modal/modal.tsx
  apps/pick-learn/src/features/auth/ui/steps/SignUpStep3.tsx
  apps/pick-learn/src/views/auth/ui/SignUpContainer.tsx
  turbo.json
Labels: refactor

#134 refactor: footer border css 수정
  apps/pick-learn/src/widgets/layout/ui/Footer.tsx
Labels: refactor

#138 feat: chat service app setting
  apps/chat-service/.gitignore
  apps/chat-service/README.md
  apps/chat-service/eslint.config.mjs
  apps/chat-service/next.config.ts
  apps/chat-service/package.json
  apps/chat-service/postcss.config.mjs
  apps/chat-service/public/file.svg
  apps/chat-service/public/globe.svg
  apps/chat-service/public/next.svg
  apps/chat-service/public/vercel.svg
  apps/chat-service/public/window.svg
  apps/chat-service/src/app/favicon.ico
  apps/chat-service/src/app/globals.css
  apps/chat-service/src/app/layout.tsx
  apps/chat-service/src/app/page.tsx
  apps/chat-service/src/shared/assets/fonts/index.ts
  apps/chat-service/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: enhancement

#141 feat: 이미지섹션 추가
  apps/pick-learn/src/shared/assets/icons/NoBoxShared.tsx
  apps/pick-learn/src/views/profile/ui/ProfileImage.tsx
  apps/pick-learn/src/views/profile/ui/ProfileImageSection.tsx
  apps/pick-learn/src/views/profile/ui/SharedButton.tsx
Labels: enhancement

#137 feat: profile page생성 및 로그인시 프로필 버튼 나오도록 추가
  apps/pick-learn/src/app/(home)/profile/page.tsx
  apps/pick-learn/src/shared/assets/icons/Profile.tsx
  apps/pick-learn/src/shared/model/constants/routes.ts
  apps/pick-learn/src/widgets/layout/ui/ProfileButton.tsx
  apps/pick-learn/src/widgets/layout/ui/SignButton.tsx
Labels: enhancement

#143 feat: 프로필 활동 내역 섹션 추가
  apps/pick-learn/src/entities/post/api/types.ts
  apps/pick-learn/src/entities/profile/api/indext.ts
  apps/pick-learn/src/entities/profile/api/types.ts
  apps/pick-learn/src/views/profile/ui/MyActiveCardList.tsx
  apps/pick-learn/src/views/profile/ui/ProfileMenu.tsx
  apps/pick-learn/src/views/profile/ui/ProfileMenuSection.tsx
Labels: enhancement

#146 refactor: profile 코드리뷰 수정사항 수정
  apps/pick-learn/src/app/(home)/profile/page.tsx
  apps/pick-learn/src/views/profile/ui/ProfileMenu.tsx
  pnpm-lock.yaml
Labels: refactor

#156 feat: meeting heading publish
  apps/chat-service/next.config.ts
  apps/chat-service/src/app/(home)/meeting/[id]/page.tsx
  apps/chat-service/src/app/(home)/meeting/page.tsx
  apps/chat-service/src/entities/meeting/model/constants.ts
  apps/chat-service/src/entities/meeting/model/types.ts
  apps/chat-service/src/entities/profile/model/constants.ts
  apps/chat-service/src/entities/profile/ui/Profile.tsx
  apps/chat-service/src/shared/assets/icons/VerticalEllipsis.tsx
  apps/chat-service/src/shared/ui/Heading.tsx
  apps/chat-service/src/shared/ui/index.ts
  apps/chat-service/src/shared/utils/dateFormat.ts
  apps/chat-service/src/views/meeting/ui/MeetingDetailHeading.tsx
  apps/chat-service/src/views/meeting/ui/MeetingParticipants.tsx
Labels: enhancement

#159 fix: build시 발생하는 warning 에러 수정
  apps/pick-learn/src/middleware.ts
Labels: bug

#177 feat: post생성에서 사용하는 input 추가 및 라이브러리 다운
  apps/pick-learn/package.json
  apps/pick-learn/src/shared/ui/Input/Input.tsx
  apps/pick-learn/src/shared/ui/Input/ResizableImageComponent.tsx
  apps/pick-learn/src/shared/ui/Input/TextArea.tsx
  apps/pick-learn/src/shared/ui/Input/Tiptap.module.css
  apps/pick-learn/src/shared/ui/Input/index.ts
  apps/pick-learn/src/shared/ui/SelectBox/SelectBox.tsx
  apps/pick-learn/src/shared/ui/SelectBox/index.ts
  pnpm-lock.yaml
Labels: enhancement

#181 feat: zod 및 postcreate api 추가
  apps/pick-learn/src/features/post/api/index.ts
  apps/pick-learn/src/features/post/api/types.ts
  apps/pick-learn/src/features/post/model/schema.ts
Labels: enhancement

#184 feat: postDetail page에 postdetailcategorySection 추가 및 api 연동
  apps/pick-learn/src/app/(home)/post/[id]/page.tsx
  apps/pick-learn/src/entities/category/api/index.ts
  apps/pick-learn/src/views/postDetail/ui/PostDetailCategorySection.tsx
  turbo.json
Labels: enhancement

#186 feat: fetch 추가 및 globalcss 추가
  apps/pick-learn/src/app/globals.css
  apps/pick-learn/src/features/post/model/hooks/fetch/serverFetch.ts
  apps/pick-learn/src/features/post/model/hooks/fetch/withServerError.ts
Labels: enhancement

#188 postdetail페이지 css 수정 및 header css 수정
  apps/pick-learn/src/shared/ui/wrapper/SectionWrapper.tsx
  apps/pick-learn/src/views/postDetail/ui/BreadCrumbSection.tsx
  apps/pick-learn/src/widgets/layout/ui/Header.tsx
Labels: refactor

#190 fix: authOptions로 getServerSession을 받아올 수 있도록 수정
  apps/chat-service/src/shared/api/instance.ts
  apps/pick-learn/src/shared/api/instance.ts
Labels: bug

#192 feat: postwriteButton 생성및 게시물 생성페이지 생성
  apps/pick-learn/src/app/(home)/post/create/page.tsx
  apps/pick-learn/src/entities/category/ui/AskAtCategoryList.tsx
  apps/pick-learn/src/features/post/ui/PostWriteForm.tsx
  apps/pick-learn/src/features/post/ui/PostWriteTopSection.tsx
  apps/pick-learn/src/shared/model/constants/routes.ts
  apps/pick-learn/src/shared/ui/wrapper/InputWrap.tsx
  apps/pick-learn/src/views/home/model/constants.ts
  apps/pick-learn/src/views/home/ui/PostWriteButton.tsx
  apps/pick-learn/src/views/home/ui/StepSection.tsx
  apps/pick-learn/src/views/postDetail/ui/PostDetailContentSection.tsx
Labels: enhancement, refactor

#194 fix: 경로오류 수정
  apps/pick-learn/src/views/home/model/constants.ts
Labels: bug

#202 feat: 프로필페이지 api 연동 및 프로필이미지 없을 시 fallbacklist 에서 랜덤으로 출력 되도록 fallbac…
  apps/pick-learn/src/app/(home)/profile/page.tsx
  apps/pick-learn/src/entities/profile/api/index.ts
  apps/pick-learn/src/entities/profile/api/types.ts
  apps/pick-learn/src/views/profile/ui/ProfileImage.tsx
  apps/pick-learn/src/views/profile/ui/ProfileImageSection.tsx
  apps/pick-learn/src/views/profile/ui/ProfileInfoSection.tsx
Labels: enhancement

#203 feat: openvidu boilerplate
  apps/chat-service/package.json
  apps/chat-service/src/entities/profile/ui/Avatar.tsx
  apps/chat-service/src/entities/profile/ui/Profile.tsx
  apps/chat-service/src/features/video-call/api/index.ts
  apps/chat-service/src/features/video-call/libs/attachSessionListeners.ts
  apps/chat-service/src/features/video-call/libs/createOpenViduSession.ts
  apps/chat-service/src/features/video-call/libs/startCall.ts
  apps/chat-service/src/features/video-call/libs/stopCall.ts
  apps/chat-service/src/features/video-call/model/context.tsx
  apps/chat-service/src/features/video-call/model/types.ts
  apps/chat-service/src/features/video-call/ui/PublisherVideo.tsx
  apps/chat-service/src/features/video-call/ui/SessionToggleButton.tsx
  apps/chat-service/src/features/video-call/ui/VideoRoom.tsx
  apps/chat-service/src/shared/api/constants.ts
  apps/chat-service/src/shared/assets/icons/VerticalEllipsis.tsx
  apps/chat-service/src/shared/ui/Heading.tsx
  apps/chat-service/src/views/meeting/ui/MeetingParticipants.tsx
  apps/chat-service/src/widgets/layout/ui/Header.tsx
  apps/chat-service/src/widgets/layout/ui/Nav.tsx
  apps/chat-service/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#211 feat: chat room UI
  apps/chat-service/package.json
  apps/chat-service/src/app/(home)/messages/page.tsx
  apps/chat-service/src/entities/chat/model/constants.ts
  apps/chat-service/src/entities/chat/ui/ChatGroup.tsx
  apps/chat-service/src/entities/chat/ui/ChatItem.tsx
  apps/chat-service/src/entities/chatRoom/api/index.ts
  apps/chat-service/src/entities/chatRoom/model/constants.ts
  apps/chat-service/src/entities/chatRoom/ui/ChatRoomItem.tsx
  apps/chat-service/src/entities/profile/api/index.ts
  apps/chat-service/src/entities/profile/ui/Avatar.tsx
  apps/chat-service/src/features/video-call/api/index.ts
  apps/chat-service/src/features/video-call/libs/startCall.ts
  apps/chat-service/src/features/video-call/model/context.tsx
  apps/chat-service/src/features/video-call/ui/CreateChatForm.tsx
  apps/chat-service/src/features/video-call/ui/StartVideoButton.tsx
  apps/chat-service/src/features/video-call/ui/StopVideoButton.tsx
  apps/chat-service/src/features/video-call/ui/VideoRoom.tsx
  apps/chat-service/src/shared/assets/icons/StopCall.tsx
  apps/chat-service/src/shared/assets/icons/Video.tsx
  apps/chat-service/src/shared/utils/dateFormat.ts
  apps/chat-service/src/views/chatList/ui/ChatRoomListSection.tsx
  apps/chat-service/src/views/chatList/ui/ChatRoomSection.tsx
  packages/ui/src/styles/default.css
  pnpm-lock.yaml
Labels: enhancement, refactor

#210 feat: 프로필 정보 수정 추가
  apps/pick-learn/src/app/(home)/profile/[memberUuid]/page.tsx
  apps/pick-learn/src/app/api/s3/client/route.ts
  apps/pick-learn/src/entities/activeHistory/api/index.ts
  apps/pick-learn/src/entities/activeHistory/ui/MyQuestionList.tsx
  apps/pick-learn/src/entities/activeHistory/ui/MyReviewList.tsx
  apps/pick-learn/src/entities/member/ui/Profile.tsx
  apps/pick-learn/src/entities/post/ui/PostCard.tsx
  apps/pick-learn/src/entities/profile/api/constants.ts
  apps/pick-learn/src/entities/profile/api/index.ts
  apps/pick-learn/src/entities/profile/api/types.ts
  apps/pick-learn/src/features/profile/api/index.ts
  apps/pick-learn/src/features/profile/api/types.ts
  apps/pick-learn/src/features/profile/model/schema.ts
  apps/pick-learn/src/features/profile/ui/NickNameEditModal.tsx
  apps/pick-learn/src/features/profile/ui/ProfileNickNameChangeButton.tsx
  apps/pick-learn/src/features/profile/ui/SelfIntroduction.tsx
  apps/pick-learn/src/shared/api/s3-service.ts
  apps/pick-learn/src/shared/assets/icons/Pencil.tsx
  apps/pick-learn/src/shared/ui/Input/Tiptap.tsx
  apps/pick-learn/src/views/home/ui/AskItemCardList.tsx
  apps/pick-learn/src/views/profile/ui/ActivityTabWrapper.tsx
  apps/pick-learn/src/views/profile/ui/MyActiveCardList.tsx
  apps/pick-learn/src/views/profile/ui/MyCategoryList.tsx
  apps/pick-learn/src/views/profile/ui/ProfileImage.tsx
  apps/pick-learn/src/views/profile/ui/ProfileInfoSection.tsx
  apps/pick-learn/src/views/profile/ui/ProfileNickNameGrade.tsx
  apps/pick-learn/src/views/profile/ui/SelfIntroduction.tsx
Labels: enhancement

#220 chore : Frontend Deploy to ECR and EC2
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
  apps/chat-service/next.config.ts
  apps/chat-service/package.json
  apps/pick-learn/package.json
  docker-compose-front.yml
  turbo.json
Labels: enhancement
