Repository Learn-Run/front, pull requests merged in 2025-05, with the labels that each got.

#12 feat: label 생성
  apps/pick-learn/src/entities/post/ui/rankLabel.tsx
  apps/pick-learn/src/shared/assets/icons/star.tsx
  apps/pick-learn/src/shared/ui/index.ts
  apps/pick-learn/src/shared/ui/label.tsx
Labels: enhancement

#17 feat: 공통 컴포넌트 Stepper 추가
  packages/ui/src/components/base/Stepper.tsx
Labels: enhancement

#22 feat: input 컴포넌트 추가
  apps/pick-learn/src/shared/assets/icons/Check.tsx
  packages/ui/src/components/base/Input/index.tsx
  packages/ui/src/components/base/Input/types.ts
Labels: enhancement

#27 feat: heading 공통 컴포넌트 생성
  apps/pick-learn/src/app/(home)/page.tsx
  apps/pick-learn/src/app/layout.tsx
  apps/pick-learn/src/widgets/home/ui/Heading.tsx
  apps/pick-learn/src/widgets/layout/ui/Footer.tsx
  apps/pick-learn/src/widgets/layout/ui/Header.tsx
  apps/pick-learn/src/widgets/layout/ui/Nav.tsx
Labels: enhancement

#29 refactor: button outline 색상 변경
  apps/pick-learn/src/widgets/layout/ui/Header.tsx
  packages/ui/src/components/base/Button.tsx
Labels: refactor

#32 feat: auth에서 사용되는 heading 컴포넌트 추가
  apps/pick-learn/src/features/auth/ui/AuthHeading.tsx
  apps/pick-learn/src/features/auth/ui/index.ts
Labels: enhancement

#40 feat: main step section 생성
  apps/pick-learn/src/app/(home)/page.tsx
  apps/pick-learn/src/shared/assets/icons/PopularAsker.tsx
  apps/pick-learn/src/shared/assets/icons/StepAnswer.tsx
  apps/pick-learn/src/shared/assets/icons/StepSearch.tsx
  apps/pick-learn/src/shared/assets/icons/index.ts
  apps/pick-learn/src/views/home/model/constants.ts
  apps/pick-learn/src/views/home/ui/StepSection.tsx
  apps/pick-learn/src/widgets/home/ui/Heading.tsx
  apps/pick-learn/src/widgets/home/ui/StepCard.tsx
  apps/pick-learn/src/widgets/layout/constants.ts
  apps/pick-learn/src/widgets/layout/ui/BottomNavBar.tsx
  apps/pick-learn/src/widgets/layout/ui/Nav.tsx
  apps/pick-learn/src/widgets/layout/ui/SubMenu.tsx
  packages/ui/package.json
  packages/ui/src/components/base/Carousel.tsx
  pnpm-lock.yaml
Labels: enhancement

#42 feat: casrousel 적용
  .bash_porfile
  .gitignore
  apps/pick-learn/src/app/(home)/page.tsx
  apps/pick-learn/src/features/auth/ui/index.ts
  apps/pick-learn/src/shared/assets/icons/index.ts
  apps/pick-learn/src/shared/ui/Tag.tsx
  apps/pick-learn/src/shared/ui/index.ts
  apps/pick-learn/src/views/home/ui/StepCardCarousel.tsx
  apps/pick-learn/src/views/home/ui/StepCardList.tsx
  apps/pick-learn/src/views/home/ui/StepSection.tsx
  apps/pick-learn/src/views/home/ui/index.ts
  apps/pick-learn/src/widgets/auth/utils/index.ts
  apps/pick-learn/src/widgets/home/ui/Heading.tsx
  apps/pick-learn/src/widgets/home/ui/StepCard.tsx
  apps/pick-learn/src/widgets/layout/ui/index.ts
  package.json
Labels: enhancement

#44 refactor: mainwrapper 추가 및 root layout 수정
  apps/pick-learn/src/app/layout.tsx
  apps/pick-learn/src/shared/ui/Wrapper/MainWrapper.tsx
  apps/pick-learn/src/shared/ui/index.ts
Labels: enhancement, refactor

#46 Refactor/hero
  apps/pick-learn/src/app/(home)/page.tsx
  apps/pick-learn/src/views/home/ui/HeroSection.tsx
  apps/pick-learn/src/views/home/ui/StepSection.tsx
Labels: refactor
